services:
  fashion-graph:
    # image creation
    build: .
    image: fashion-graph-image
    pull_policy: never
    container_name: fashion-graph-container

    # runtime
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - SUBREDDIT_NAME=${SUBREDDIT_NAME:-python}
      - POST_LIMIT=${POST_LIMIT:-10}
    volumes:
      - ./output:/app/output
