services:
  fashion-graph:
    # image creation
    build: .
    image: fashion-graph-image
    pull_policy: never
    container_name: fashion-graph-container

    # runtime
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - SEARCH_TERM=${SEARCH_TERM:-python}
      - SEARCH_SORT=${SEARCH_SORT:-relevance}
      - TIME_FILTER=${TIME_FILTER:-all}
      - POST_LIMIT=${POST_LIMIT:-10}
      - PHASE=${PHASE:-1}
    volumes:
      - .:/app # map the entire app for quick development
